# Generated by Django 3.2.10 on 2022-02-24 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasifiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('puntuacion', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipotrabajo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrehabilidad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='Sin Descripcion', max_length=1000)),
                ('nomeroTrabjos', models.IntegerField(default=0)),
                ('tipoTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipotrabajo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoValoracion', models.ImageField(upload_to='DeTodoTrabajo/fotoValoracion/')),
                ('clasifiacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clasifiacion')),
            ],
        ),
        migrations.CreateModel(
            name='FotoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoTrabajo', models.ImageField(upload_to='DeTodoTrabajo/FotoTrabajo/')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.habilidades')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='DeTodoTrabajo/FotoUser/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('Direcion', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
